parameters:
    mk.tag_manager.class: Mykees\TagBundle\Manager\TagManager
services:
#    mykees_tag.example:
#        class: Mykees\TagBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    mk.tag_manager:
        class: Mykees\TagBundle\Manager\TagManager
        arguments: ["@doctrine"]

    mk.tag.form:
        class: Mykees\TagBundle\Form\TagType
        arguments: ["@mk.tag_manager"]
        tags:
            - { name: form.type, alias: mk_tag }

    mk.tag.listener:
        class: Mykees\TagBundle\Listener\TagListener
        arguments: ["@doctrine"]
        tags:
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }
            - { name: doctrine.event_listener, event: preRemove, method: preRemove }

    mykees.twig.tag_extension:
        class: Mykees\TagBundle\Twig\Extension\TagExtension
        tags:
            - { name: twig.extension, alias: mykees_tag_extension }
