parameters:
    mk.tag.manager.class: Mykees\TagBundle\Manager\TagManager
services:
#    mykees_tag.example:
#        class: Mykees\TagBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    mk.tag.manager:
        class: Mykees\TagBundle\Manager\TagManager
        arguments: ["@doctrine.orm.entity_manager"]

    mk.tag.form:
        class: Mykees\TagBundle\Form\TagType
        tags:
            - { name: form.type, alias: mykees_tag_form }

    mk.tag.listener:
        class: Mykees\TagBundle\Listener\TagListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }
            - { name: doctrine.event_listener, event: preRemove, method: preRemove }

    mykees.twig.tag_extension:
        class: Mykees\TagBundle\Twig\Extension\TagExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension, alias: mykees_tag_extension }