language: php

php:
    - 5.6

env:
    - SYMFONY_VERSION=2.6.*

before_script:
    - mysql -e "create database test;"
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION}
    - composer install --dev
    - php Tests/Fixtures/bin/console --env=test doctrine:schema:create
    - php Tests/Fixtures/bin/console --env=test doctrine:schema:update --force
    - php Tests/Fixtures/bin/console --env=test assetic:dump


after_script:
    - php Tests/Fixtures/bin/console --env=test doctrine:database:drop --force

script:
    - phpunit
